# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dummy_pb2 as dummy__pb2


class MessagingStub(object):
    """defining the service itself
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.unary_unary(
                '/grpc.Messaging/send',
                request_serializer=dummy__pb2.TextMessage.SerializeToString,
                response_deserializer=dummy__pb2.Empty.FromString,
                )
        self.receive = channel.unary_stream(
                '/grpc.Messaging/receive',
                request_serializer=dummy__pb2.Member.SerializeToString,
                response_deserializer=dummy__pb2.TextMessage.FromString,
                )


class MessagingServicer(object):
    """defining the service itself
    """

    def send(self, request, context):
        """the sending send only one message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def receive(self, request, context):
        """receiving multiple messages
        receive send the person object who wants to receive
        and returns a stream of Text messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=dummy__pb2.TextMessage.FromString,
                    response_serializer=dummy__pb2.Empty.SerializeToString,
            ),
            'receive': grpc.unary_stream_rpc_method_handler(
                    servicer.receive,
                    request_deserializer=dummy__pb2.Member.FromString,
                    response_serializer=dummy__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Messaging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Messaging(object):
    """defining the service itself
    """

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Messaging/send',
            dummy__pb2.TextMessage.SerializeToString,
            dummy__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def receive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Messaging/receive',
            dummy__pb2.Member.SerializeToString,
            dummy__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
